# Generated by Django 5.0.7 on 2024-07-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
